ToDo.Web/Models/ErrorViewModel.cs
namespace ToDo.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDo.Web/Models/ToDo/CreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ToDo.Web.Models.ToDo
{
    public class CreateViewModel
    {
        [Required]
        [MaxLength(128)]
        public string Name { get; set; }
    }
}

ToDo.Web/Models/ToDo/DeleteViewModel.cs
using System;

namespace ToDo.Web.Models.ToDo
{
    public class DeleteViewModel
    {
        public Guid Id { get; set; }
        public string Name{ get; set; }
    }
}

ToDo.Web/Models/ToDo/UpdateViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ToDo.Web.Models.ToDo
{
    public class UpdateViewModel
    {
        public Guid Id { get; set; }
        [Required]
        [MaxLength(128)]
        public string Name{ get; set; }
    }
}

ToDo.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ToDo.Web.Models;

namespace ToDo.Web.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

ToDo.Web/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using ToDo.Dto;
using ToDo.Services;
using ToDo.Web.Models.ToDo;

namespace ToDo.Web.Controllers
{
    public class ToDoController : Controller
    {
        private readonly IToDoItemService _toDoItemService;

        public ToDoController(IToDoItemService toDoItemService)
        {
            this._toDoItemService = toDoItemService ?? throw new ArgumentNullException(nameof(toDoItemService));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var items = await _toDoItemService.GetItemsAsync();
            return View(items);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            await _toDoItemService.AddItemAsync(new ToDoItem() {Name = model.Name});
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var item = await _toDoItemService.GetAsync(id);

            if (item == null)
                return NotFound();

            var model = new UpdateViewModel() {Id = item.Id, Name = item.Name};
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UpdateViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            await _toDoItemService.UpdateItemAsync(new ToDoItem() {Id = model.Id, Name = model.Name});
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await _toDoItemService.GetAsync(id);

            if (item == null)
                return NotFound();

            var model = new DeleteViewModel() {Id = item.Id, Name = item.Name};
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(DeleteViewModel model)
        {
            await _toDoItemService.DeleteItemAsync(model.Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ToDo.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Your ToDo items are listed in <a asp-action="Index" asp-controller="ToDo">ToDos</a>.</p>
</div>

ToDo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDo.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">ToDos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ToDo.Web
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ToDo.Web/Views/ToDo/Create.cshtml
@using ToDo.Web.Models.ToDo
@model CreateViewModel
@{
    ViewData["Title"] = "New item";
}

<h1 class="display-4">New item</h1>
<form asp-action="@nameof(ToDo.Web.Controllers.ToDoController.Create)">
    @Html.AntiForgeryToken()
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

ToDo.Web/Views/ToDo/Delete.cshtml
@using ToDo.Web.Models.ToDo
@model DeleteViewModel
@{
    ViewData["Title"] = $"Delete {Model.Name}";
}

<h1 class="display-4">Delete @Model.Name?</h1>
<form asp-action="@nameof(ToDo.Web.Controllers.ToDoController.Delete)">
    @Html.AntiForgeryToken()
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <input type="submit" value="Delete" class="btn btn-danger" />
    </div>
</form>

ToDo.Web/Views/ToDo/Index.cshtml
@using ToDo.Dto
@model IEnumerable<ToDoItem>
@{
    ViewData["Title"] = "My ToDos";
}

<h1 class="display-4">My ToDos</h1>
<div class="mt-5"></div>
<ul>
    @foreach (var item in Model)
    {
    <li class="todo-item">
        <a asp-action="@nameof(ToDo.Web.Controllers.ToDoController.Update)" asp-route-id="@item.Id">@item.Name</a>
        |
        <a asp-action="@nameof(ToDo.Web.Controllers.ToDoController.Delete)" asp-route-id="@item.Id">Delete</a>
    </li>
    }
</ul>
<div class="mt-5"></div>
<a asp-action="Create" class="btn btn-primary">New item</a>

ToDo.Web/Views/ToDo/Update.cshtml
@using ToDo.Web.Models.ToDo
@model UpdateViewModel
@{
    ViewData["Title"] = $"Edit {Model.Name}";
}

<h1 class="display-4">Edit @Model.Name</h1>
<form asp-action="@nameof(ToDo.Web.Controllers.ToDoController.Update)">
    @Html.AntiForgeryToken()
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>